src/Entity/Annonce.php
<?php

namespace App\Entity;

use App\Repository\AnnonceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AnnonceRepository::class)
 */
class Annonce
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="date")
     */
    private $date_creation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type_article;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $matiere;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $couleur;

    /**
     * @ORM\Column(type="float")
     */
    private $longueur;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $largeur;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $hauteur;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $etat;

    /**
     * @ORM\Column(type="text")
     */
    private $histoire;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prix_plancher;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prix_minimum;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prix_moyen;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prix_maximum;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $img1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img3;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img4;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="annonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;

    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="annonce")
     */
    private $notes;

    /**
     * @ORM\ManyToOne(targetEntity=Collec::class, inversedBy="annonces")
     */
    private $collec;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="fetiche")
     */
    private $feticheUsers;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="annonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $annonceUser;

    public function __construct()
    {
        $this->notes = new ArrayCollection();
        $this->feticheUsers = new ArrayCollection();
    }
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getTypeArticle(): ?string
    {
        return $this->type_article;
    }

    public function setTypeArticle(?string $type_article): self
    {
        $this->type_article = $type_article;

        return $this;
    }

    public function getMatiere(): ?string
    {
        return $this->matiere;
    }

    public function setMatiere(string $matiere): self
    {
        $this->matiere = $matiere;

        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    public function setCouleur(string $couleur): self
    {
        $this->couleur = $couleur;

        return $this;
    }

    public function getLongueur(): ?float
    {
        return $this->longueur;
    }

    public function setLongueur(float $longueur): self
    {
        $this->longueur = $longueur;

        return $this;
    }

    public function getLargeur(): ?float
    {
        return $this->largeur;
    }

    public function setLargeur(?float $largeur): self
    {
        $this->largeur = $largeur;

        return $this;
    }

    public function getHauteur(): ?float
    {
        return $this->hauteur;
    }

    public function setHauteur(?float $hauteur): self
    {
        $this->hauteur = $hauteur;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getHistoire(): ?string
    {
        return $this->histoire;
    }

    public function setHistoire(string $histoire): self
    {
        $this->histoire = $histoire;

        return $this;
    }

    public function getPrixPlancher(): ?float
    {
        return $this->prix_plancher;
    }

    public function setPrixPlancher(?float $prix_plancher): self
    {
        $this->prix_plancher = $prix_plancher;

        return $this;
    }

    public function getPrixMinimum(): ?float
    {
        return $this->prix_minimum;
    }

    public function setPrixMinimum(?float $prix_minimum): self
    {
        $this->prix_minimum = $prix_minimum;

        return $this;
    }

    public function getPrixMoyen(): ?float
    {
        return $this->prix_moyen;
    }

    public function setPrixMoyen(?float $prix_moyen): self
    {
        $this->prix_moyen = $prix_moyen;

        return $this;
    }

    public function getPrixMaximum(): ?float
    {
        return $this->prix_maximum;
    }

    public function setPrixMaximum(?float $prix_maximum): self
    {
        $this->prix_maximum = $prix_maximum;

        return $this;
    }

    public function getImg1(): ?string
    {
        return $this->img1;
    }

    public function setImg1(string $img1): self
    {
        $this->img1 = $img1;

        return $this;
    }

    public function getImg2(): ?string
    {
        return $this->img2;
    }

    public function setImg2(?string $img2): self
    {
        $this->img2 = $img2;

        return $this;
    }

    public function getImg3(): ?string
    {
        return $this->img3;
    }

    public function setImg3(?string $img3): self
    {
        $this->img3 = $img3;

        return $this;
    }

    public function getImg4(): ?string
    {
        return $this->img4;
    }

    public function setImg4(?string $img4): self
    {
        $this->img4 = $img4;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setAnnonce($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->removeElement($note)) {
            // set the owning side to null (unless already changed)
            if ($note->getAnnonce() === $this) {
                $note->setAnnonce(null);
            }
        }

        return $this;
    }

    public function getCollec(): ?Collec
    {
        return $this->collec;
    }

    public function setCollec(?Collec $collec): self
    {
        $this->collec = $collec;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getFeticheUsers(): Collection
    {
        return $this->feticheUsers;
    }

    public function addFeticheUser(User $user): self
    {
        if (!$this->feticheUsers->contains($user)) {
            $this->feticheUsers[] = $user;
            $user->addFetiche($this);
        }

        return $this;
    }

    public function removeFeticheUser(User $user): self
    {
        if ($this->feticheUsers->removeElement($user)) {
            $user->removeFetiche($this);
        }

        return $this;
    }

    public function getAnnonceUser(): ?User
    {
        return $this->annonceUser;
    }

    public function setAnnonceUser(?User $user): self
    {
        $this->annonceUser = $user;

        return $this;
    }

    public function __toString()
    {
        return strval($this->id);
    }
}

src/Entity/Note.php
<?php

namespace App\Entity;

use App\Repository\NoteRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=NoteRepository::class)
 */
class Note
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $note_insolite;

    /**
     * @ORM\Column(type="integer")
     */
    private $note_pratique;

    /**
     * @ORM\Column(type="integer")
     */
    private $note_style;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="notes")
     */
    private $utilisateur;

    /**
     * @ORM\ManyToOne(targetEntity=Annonce::class, inversedBy="notes")
     */
    private $annonce;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNoteInsolite(): ?int
    {
        return $this->note_insolite;
    }

    public function setNoteInsolite(int $note_insolite): self
    {
        $this->note_insolite = $note_insolite;

        return $this;
    }

    public function getNotePratique(): ?int
    {
        return $this->note_pratique;
    }

    public function setNotePratique(int $note_pratique): self
    {
        $this->note_pratique = $note_pratique;

        return $this;
    }

    public function getNoteStyle(): ?int
    {
        return $this->note_style;
    }

    public function setNoteStyle(int $note_style): self
    {
        $this->note_style = $note_style;

        return $this;
    }

    public function getUtilisateur(): ?User
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?User $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getAnnonce(): ?Annonce
    {
        return $this->annonce;
    }

    public function setAnnonce(?Annonce $annonce): self
    {
        $this->annonce = $annonce;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email')
            ->add('roles')
            ->add('password')
            ->add('pseudo')
            ->add('statut')
            ->add('prenom')
            ->add('nom')
        ;
        $builder->get('roles')
            ->addModelTransformer(new CallbackTransformer(
                function ($rolesAsArray) {
                    // transform the array to a string
                    return implode(', ', $rolesAsArray);
                },
                function ($rolesAsString) {
                    // transform the string back to an array
                    return explode(', ', $rolesAsString);
                }
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Entity\Annonce;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }
    
    #[Route('/fetiches', name: 'user_fetiches', methods: ['GET'])] // Liste des fétiches d'un user
    public function userFeticheIndex(): Response
    {
        $user = $this->getUser();
        return $this->render('user/fetiches.html.twig', [
            'annonces' => $user->getFetiche(),
        ]);
    }

    #[Route('/fetiche/{id}', name: 'user_fetiche', methods: ['GET'])] // Détail d'un fétiche user
    public function userFeticheDetail(Annonce $annonce): Response
    {
        return $this->render('user/fetiche.html.twig', [
            'annonce' => $annonce,
        ]);
    }

    #[Route('/annonces', name: 'user_annonces', methods: ['GET'])] // Liste des annonces d'un user
    public function userAnnonceIndex(): Response
    {
        $user = $this->getUser();
        return $this->render('user/annonces.html.twig', [
            'annonces' => $user->getAnnonces(),
        ]);
    }

    #[Route('/annonce/{id}', name: 'user_annonce', methods: ['GET'])] // Détail d'une annonce user
    public function userAnnonceDetail(Annonce $annonce): Response
    {
        return $this->render('user/annonce.html.twig', [
            'annonce' => $annonce,
        ]);
    }

    #[Route('/notes', name: 'user_notes', methods: ['GET'])] // Template Liste des notes d'un user à finaliser
    public function userNoteIndex(): Response
    {
        $user = $this->getUser();
        return $this->render('user/notes.html.twig', [
            'annonces' => $user->getNotes(),
        ]);
    }

    #[Route('/{id}', name: 'user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/annonce.html.twig
{% extends 'base.html.twig' %}

{% block title %}User-Annonce{% endblock %}

{% block body %}
<header class="container-fluid p-5 text-center bg-light">
    <h1>{{ annonce.titre }}</h1>
</header>

<main class="container-fluid">
    <div class="row p-5">
        <div class="col-8 offset-2">
            <img src="{{ asset('img/annonce/' ~ annonce.img1) }}" alt="photo principale {{ annonce.titre }}" class="w-100">
            <h2 class="py-3">{{ annonce.titre }}</h2>
            <p>{{ annonce.dateCreation ? annonce.dateCreation|date('d-m-Y') : '' }}</p>
            <p>{{ annonce.histoire }}</p>
            <ul>
                <li>{{ annonce.categorie }}</li>
                <li>{{ annonce.typeArticle }}</li>
                <li>{{ annonce.matiere }}</li>
                <li>{{ annonce.couleur }}</li>
                <li>{{ annonce.longueur }} cm</li>
                <li>{{ annonce.largeur }} cm</li>
                <li>{{ annonce.hauteur }} cm</li>
                <li>{{ annonce.etat }}</li>
                <li>{{ annonce.prixPlancher|number_format(0, ',', ' ') }} €</li>
                <li>{{ annonce.prixMinimum|number_format(0, ',', ' ') }} €</li>
                <li>{{ annonce.prixMoyen|number_format(0, ',', ' ') }} €</li>
                <li>{{ annonce.prixMaximum|number_format(0, ',', ' ') }} €</li>
                <li>{{ annonce.collec }}</li>
            </ul>
        </div>
        {% if annonce.img2 is not null %}
            <div class="col-4 offset-2">
                <h2 class="py-3">Autres photos</h2>
                <img src="{{ asset('img/annonce/' ~ annonce.img2) }}" alt="photo 2 {{ annonce.titre }}" class="w-100">
            </div>
        {% endif %}

        {% if annonce.img3 is not null %}
            <div class="col-4 offset-2">
                <img src="{{ asset('img/annonce/' ~ annonce.img3) }}" alt="photo 3 {{ annonce.titre }}" class="w-100">
            </div>
        {% endif %}

        {% if annonce.img4 is not null %}
            <div class="col-4 offset-2">
                <img src="{{ asset('img/annonce/' ~ annonce.img4) }}" alt="photo 4 {{ annonce.titre }}" class="w-100">
            </div>
        {% endif %}
    </div>
</main>

    

    <a href="{{ path('user_annonces') }}">back to list</a> <!--Retour à la liste générale des annonces > pour tous-->

    <a href="{{ path('annonce_edit', {'id': annonce.id}) }}">edit</a> <!--Seul le User-D peut avoir accès à l'edit > assimilé à un admin-->

    <!-- {{ include('annonce/_delete_form.html.twig') }} Le User peut-il supprimer son annonce ici ?-->
{% endblock %}

templates/user/annonces.html.twig
{% extends 'base.html.twig' %}

{% block title %}User-Annonces{% endblock %}
   
{% block body %}
    
    <header class="container-fluid p-5 text-center bg-light">
       <h1>Mes Annonces</h1>
    </header> 

    <main class="container-fluid p-5">
        <div class="row">   
            {% for annonce in annonces|reverse %}
                <div class="row col-4 p-3">
                    <div class="card">
                        <img src="{{ asset('assets/annonce/' ~ annonce.img1) }}" class="card-img-top" alt="photo principale de {{ annonce.titre }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ annonce.titre }}</h5>
                            <p>{{ annonce.dateCreation ? annonce.dateCreation|date('d-m-Y') : '' }}</p>
                            <p class="card-text">{{ annonce.histoire|u.truncate(75, '...', false) }}</p>
                        </div>
                        <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{ annonce.categorie }}</li>
                        <li class="list-group-item">{{ annonce.typeArticle }}</li>
                        <li class="list-group-item">{{ annonce.matiere }}</li>
                        <li class="list-group-item">{{ annonce.couleur }}</li>
                        <li class="list-group-item">Dimensions (en cm) : L {{ annonce.longueur }} - l {{ annonce.largeur }} - H {{ annonce.hauteur }}</li>
                        <li class="list-group-item">{{ annonce.etat }}</li>
                        <li class="list-group-item">Prix plancher : {{ annonce.prixPlancher|number_format(0, ',', ' ') }} €</li>
                        <li class="list-group-item">Prix minimum : {{ annonce.prixMinimum|number_format(0, ',', ' ') }} €</li>
                        <li class="list-group-item">Prix moyen : {{ annonce.prixMoyen|number_format(0, ',', ' ') }} €</li>
                        <li class="list-group-item">Prix maximum : {{ annonce.prixMaximum|number_format(0, ',', ' ') }} €</li>
                        <li class="list-group-item">Appartient à la collection: {{ annonce.collec }}</li>
                        </ul>
                        <div class="card-body text-center">
                        <a href="{{ path('user_annonce', {'id': annonce.id}) }}" class="btn btn-secondary">Voir détail</a>
                        </div>
                    </div>
                </div>
                
                <!-- <a href="{{ path('annonce_show', {'id': annonce.id}) }}">voir</a> // Lien à traiter pour le User idem fetiche/user-->
                <!-- <a href="{{ path('annonce_edit', {'id': annonce.id}) }}">modifier</a> // dans l'admin_annonce ???-->
        
        {% else %}
            <tr>
                <td colspan="20">no records found</td>
            </tr>
        {% endfor %}
{% endblock %}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/fetiche.html.twig
{% extends 'base.html.twig' %}

{% block title %}User-Fétiche{% endblock %}

{% block body %}
    
<header class="container-fluid p-5 text-center bg-light">
    <h1>Annonce - fétiche</h1>
</header>

<main class="container-fluid">
    <div class="row p-5">
        <div class="col-8 offset-2">
            <img src="{{ asset('assets/annonce/' ~ annonce.img1) }}" alt="photo principale {{ annonce.titre }}" class="w-100">
            <h2 class="py-3">{{ annonce.titre }}</h2>
            <p>{{ annonce.dateCreation ? annonce.dateCreation|date('d-m-Y') : '' }}</p>
            <p>{{ annonce.histoire }}</p>
        <div class="row p-5">
                <div class="col-5 offset-1">
                    <ul>
                        <li>{{ annonce.categorie }}</li>
                        <li>{{ annonce.typeArticle }}</li>
                        <li>{{ annonce.matiere }}</li>
                        <li>{{ annonce.couleur }}</li>
                        <li>{{ annonce.longueur }} cm</li>
                        <li>{{ annonce.largeur }} cm</li>
                        <li>{{ annonce.hauteur }} cm</li>
                        
                    </ul>
                </div>
                <div class="col-5 offset-1">
                    <ul>
                        <li>{{ annonce.etat }}</li>
                        <li>{{ annonce.prixPlancher|number_format(0, ',', ' ') }} €</li>
                        <li>{{ annonce.prixMinimum|number_format(0, ',', ' ') }} €</li>
                        <li>{{ annonce.prixMoyen|number_format(0, ',', ' ') }} €</li>
                        <li>{{ annonce.prixMaximum|number_format(0, ',', ' ') }} €</li>
                        <li>{{ annonce.collec }}</li>
                    </ul>
                </div>
            </div>
        </div>
        {% if annonce.img2 is not null %}
            <div class="col-3 offset-1">
                <h2 class="py-3">Autres photos</h2>
                <img src="{{ asset('img/annonce/' ~ annonce.img2) }}" alt="photo 2 {{ annonce.titre }}" class="w-100">
            </div>
        {% endif %}

        {% if annonce.img3 is not null %}
            <div class="col-3 offset-1">
                <img src="{{ asset('img/annonce/' ~ annonce.img3) }}" alt="photo 3 {{ annonce.titre }}" class="w-100">
            </div>
        {% endif %}

        {% if annonce.img4 is not null %}
            <div class="col-3 offset-1">
                <img src="{{ asset('img/annonce/' ~ annonce.img4) }}" alt="photo 4 {{ annonce.titre }}" class="w-100">
            </div>
        {% endif %}
    </div>
</main>

    <a href="{{ path('fetiches_delete', {'id': annonce.id}) }}">Retirer le fétiche</a>
    <a href="{{ path('user_fetiches') }}">Retour à la liste</a>

    <!-- <a href="{# path('fetiches_edit', {'id': annonce.id}) #}">edit</a> -->

{% endblock %}

templates/user/fetiches.html.twig
{% extends 'base.html.twig' %}

{% block title %}User-Fetiches{% endblock %}

{% block body %}
    <h1>Mes Fétiches</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Date_creation</th>
                <th>Type_article</th>
                <th>Matiere</th>
                <th>Couleur</th>
                <th>Longueur</th>
                <th>Largeur</th>
                <th>Hauteur</th>
                <th>Etat</th>
                <th>Histoire</th>
                <th>Prix_plancher</th>
                <th>Prix_minimum</th>
                <th>Prix_moyen</th>
                <th>Prix_maximum</th>
                <th>Img1</th>
                <th>Img2</th>
                <th>Img3</th>
                <th>Img4</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for annonce in annonces %}
            <tr>
                <td>{{ annonce.id }}</td>
                <td>{{ annonce.titre }}</td>
                <td>{{ annonce.dateCreation ? annonce.dateCreation|date('Y-m-d') : '' }}</td>
                <td>{{ annonce.typeArticle }}</td>
                <td>{{ annonce.matiere }}</td>
                <td>{{ annonce.couleur }}</td>
                <td>{{ annonce.longueur }}</td>
                <td>{{ annonce.largeur }}</td>
                <td>{{ annonce.hauteur }}</td>
                <td>{{ annonce.etat }}</td>
                <td>{{ annonce.histoire }}</td>
                <td>{{ annonce.prixPlancher }}</td>
                <td>{{ annonce.prixMinimum }}</td>
                <td>{{ annonce.prixMoyen }}</td>
                <td>{{ annonce.prixMaximum }}</td>
                <td>{{ annonce.img1 }}</td>
                <td>{{ annonce.img2 }}</td>
                <td>{{ annonce.img3 }}</td>
                <td>{{ annonce.img4 }}</td>
                <td>
                    <a href="{{ path('user_fetiche', {'id': annonce.id}) }}">Voir</a>
                    
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="20">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

templates/user/notes.html.twig
{% extends 'base.html.twig' %}

{% block title %}User-Notes{% endblock %}

{% block body %}
    <h1>Mes notes</h1>
TODO: mettre en place template recoupant toutes les notes de ce user par annonce_id (et non note_id)
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Note_insolite</th>
                <th>Note_pratique</th>
                <th>Note_style</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for note in notes %}
            <tr>
                <td>{{ note.id }}</td>
                <td>{{ note.noteInsolite }}</td>
                <td>{{ note.notePratique }}</td>
                <td>{{ note.noteStyle }}</td>
                <td>
                    <a href="{{ path('note_show', {'id': note.id}) }}">show</a>
                    <a href="{{ path('note_edit', {'id': note.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('note_new') }}">Create new</a> <!--Supprimer: create_new Note à partir de show Annonce-->
{% endblock %}